// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Feed struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
	Name      string
	UserID    string
}

type FeedFollow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	FeedID    int64
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
